levels = [
    { actors_spawned_per_class = 1, size = 7 },
    { actors_spawned_per_class = 10, size = 15 },
    { actors_spawned_per_class = 100 },
    { actors_spawned_per_class = 100, size = 100 },
]
