#!/usr/bin/env python

import os
from os.path import join, dirname
import shutil

libname = "lab3"


CXXFLAGS='-static'

env = Environment(
    TOOLS=['clang', 'clang++', 'gnulink'],
    CXXFLAGS=CXXFLAGS,
)

SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    platlibname = "{}.{}.{}".format(libname, env["platform"], env["target"])
    library = env.SharedLibrary(
        "bin/{}.framework/{}".format(platlibname, platlibname),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/{}{}{}".format(libname, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)